"""Generate stub files from a spec's output_files so agents have a shared skeleton."""

from __future__ import annotations

from pathlib import Path

from po.spec.schema import ProjectSpec, TaskSpec


def generate_scaffolds(spec: ProjectSpec, project_root: Path) -> list[Path]:
    """Create minimal stub files for every output_file in the spec.

    Skips files that already exist with content (size > 0).
    Returns the list of actually-created file paths.
    """
    # Map each output file to the tasks that produce it
    file_to_tasks: dict[str, list[TaskSpec]] = {}
    for task in spec.tasks:
        for output_file in task.output_files:
            file_to_tasks.setdefault(output_file, []).append(task)

    created: list[Path] = []
    for rel_path_str, tasks in sorted(file_to_tasks.items()):
        abs_path = project_root / rel_path_str
        if abs_path.exists() and abs_path.stat().st_size > 0:
            continue

        abs_path.parent.mkdir(parents=True, exist_ok=True)
        content = _stub_content(rel_path_str, tasks)
        abs_path.write_text(content, encoding="utf-8")
        created.append(abs_path)

    return created


def _stub_content(rel_path: str, tasks: list[TaskSpec]) -> str:
    """Generate stub content appropriate for the file extension."""
    suffix = Path(rel_path).suffix.lower()

    if suffix == ".py":
        inner = "\n".join(f"    {t.id}: {t.description}" for t in tasks)
        return f'"""\nStub generated by `po plan --scaffold`.\n\nImplemented by:\n{inner}\n"""\n'

    if suffix in (".js", ".ts", ".jsx", ".tsx"):
        inner = "\n".join(f" * - {t.id}: {t.description}" for t in tasks)
        return (
            f"/**\n * Stub generated by `po plan --scaffold`.\n *\n"
            f" * Implemented by:\n{inner}\n */\n"
        )

    if suffix == ".json":
        return "{}\n"

    if suffix in (".md", ".txt"):
        inner = "\n".join(f"- {t.id}: {t.description}" for t in tasks)
        return (
            f"# {Path(rel_path).stem}\n\nStub generated by `po plan --scaffold`.\n\n"
            f"Implemented by:\n{inner}\n"
        )

    # Default: comment header
    inner = "\n".join(f"#   {t.id}: {t.description}" for t in tasks)
    return f"# Stub generated by `po plan --scaffold`.\n#\n# Implemented by:\n{inner}\n"
