"""Generate a self-testing playground spec for quick end-to-end verification."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

SPEC_FILENAME = "playground-calc.json"


def _build_spec() -> dict[str, Any]:
    """Build the playground-calc spec dictionary."""
    return {
        "project_name": "playground-calc",
        "description": "A playground calculator project for testing PO end-to-end.",
        "default_model": "haiku",
        "max_concurrency": 5,
        "global_context": (
            "This is a playground project generated by `po plan --playground`. "
            "Build a simple Python calculator package under src/calc/."
        ),
        "global_context_files": ["README.md"],
        "tasks": [
            {
                "id": "init-calc",
                "description": (
                    "Create src/calc/__init__.py with a Calculator class that has "
                    "an add(a, b) method returning a + b."
                ),
                "dependencies": [],
                "context_files": ["README.md"],
                "output_files": ["src/calc/__init__.py"],
                "verification": "python -c \"from calc import Calculator; assert Calculator().add(1, 2) == 3\"",
                "priority": 10,
                "max_budget_usd": 0.50,
                "tags": ["setup", "core"],
            },
            {
                "id": "add-subtract",
                "description": (
                    "Add a subtract(a, b) method to the Calculator class in "
                    "src/calc/__init__.py that returns a - b."
                ),
                "dependencies": ["init-calc"],
                "context_files": ["src/calc/__init__.py"],
                "output_files": ["src/calc/__init__.py"],
                "verification": "python -c \"from calc import Calculator; assert Calculator().subtract(5, 3) == 2\"",
                "priority": 8,
                "max_budget_usd": 0.50,
                "tags": ["core"],
            },
            {
                "id": "add-multiply-divide",
                "description": (
                    "Add multiply(a, b) and divide(a, b) methods to the Calculator "
                    "class in src/calc/__init__.py. divide should raise ValueError "
                    "on division by zero."
                ),
                "dependencies": ["init-calc"],
                "context_files": ["src/calc/__init__.py"],
                "output_files": ["src/calc/__init__.py"],
                "verification": (
                    "python -c \""
                    "from calc import Calculator; c = Calculator(); "
                    "assert c.multiply(3, 4) == 12; assert c.divide(10, 2) == 5.0\""
                ),
                "priority": 8,
                "max_budget_usd": 0.50,
                "tags": ["core"],
            },
            {
                "id": "write-tests",
                "description": (
                    "Create tests/test_calc.py with pytest tests for all Calculator "
                    "methods: add, subtract, multiply, divide (including division by zero)."
                ),
                "dependencies": ["add-subtract", "add-multiply-divide"],
                "context_files": ["src/calc/__init__.py"],
                "output_files": ["tests/test_calc.py"],
                "verification": "python -m pytest tests/test_calc.py -v",
                "priority": 5,
                "max_budget_usd": 0.50,
                "tags": ["testing"],
            },
            {
                "id": "add-cli",
                "description": (
                    "Create src/calc/cli.py with an argparse-based CLI that accepts "
                    "two numbers and an operation (+, -, *, /) and prints the result "
                    "using the Calculator class."
                ),
                "dependencies": ["add-subtract", "add-multiply-divide"],
                "context_files": ["src/calc/__init__.py"],
                "output_files": ["src/calc/cli.py"],
                "verification": "python -c \"from calc.cli import main; print('OK')\"",
                "priority": 5,
                "max_budget_usd": 0.50,
                "tags": ["cli"],
            },
        ],
    }


def generate_playground(project_root: Path) -> tuple[Path, list[Path]]:
    """Generate a playground-calc spec and seed files.

    Returns:
        A tuple of (spec_path, list_of_created_seed_files).

    Raises:
        FileExistsError: If the spec file already exists.
    """
    spec_path = project_root / SPEC_FILENAME

    if spec_path.exists():
        raise FileExistsError(f"Spec file already exists: {spec_path}")

    seed_files: list[Path] = []

    # Create seed directory
    calc_dir = project_root / "src" / "calc"
    calc_dir.mkdir(parents=True, exist_ok=True)

    # Create README.md if missing
    readme = project_root / "README.md"
    if not readme.exists():
        readme.write_text(
            "# playground-calc\n\nGenerated by `po plan --playground`.\n",
            encoding="utf-8",
        )
        seed_files.append(readme)

    # Write spec
    spec_data = _build_spec()
    spec_path.write_text(
        json.dumps(spec_data, indent=2) + "\n",
        encoding="utf-8",
    )

    return spec_path, seed_files
